import streamlit as st
TRANSLATIONS = {
    "zh": {
        "title": "🚦 SUMO 交互式设计器",
        "settings": "🔑 设置",
        "reset": "🔄 重置所有",
        "step1_title": "Step 1: 生成路网结构",
        "desc_label": "描述:",
        "desc_default": "生成一个三角形路网，双向2车道",
        "img_label": "草图（可在图中标注节点编号，编号以0开始）:",
        "gen_btn": "🔮 生成预览",
        "need_api": "需要 API Key",
        "ai_parsing": "AI 正在解析...",
        "step2_title": "Step 2: 确认路网结构 (人机对齐)",
        "net_preview": "🗺️ 当前路网预览",
        "edge_edit": "📝 道路属性修改 ",
        "check_hint": "请检查左侧路网是否符合预期。如果连线错误或缺少节点，请在下方描述问题，AI 将尝试修复。",
        "feedback_label": "💬 如果有问题，请在这里告诉 AI (例如: '0和2之间少了一条路'):",
        "fix_btn": "🛠️ 提交修改意见",
        "confirm_btn": "✅ 确认无误，下一步",
        "back_btn": "⬅️ 返回上一步",
        "step3_title": "Step 3: 确认路网 & 添加流量",
        "net_preview_lbl": "🗺️ 路网预览 (蓝色标签 = 边ID)",
        "flow_config": "🚗 流量配置",
        "src_edge": "起始边 (From)",
        "dst_edge": "终止边 (To)",
        "veh_count": "车辆总数",
        "start_time": "开始时间 (s)",
        "end_time": "结束时间 (s)",
        "veh_ratio": "🚙 车辆构成比例 (0.0 - 1.0)",
        "car": "轿车", "truck": "卡车", "bus": "公交", "moto": "摩托",
        "add_flow": "➕ 添加流量组",
        "clear_flow": "❌ 清空列表",
        "next_step4": "下一步: 精细化调整 (Step 4)",
        "step4_title": "Step 4: 仿真精细化调整",
        "veh_params": "🔧 车辆参数配置",
        "select_type": "选择车型进行编辑",
        "tab_tls": "🚦 交通信号灯",
        "tab_phys": "🚙 物理参数",
        "tab_model": "🧠 驾驶模型",
        "tab_sim": "⚙️ 仿真设置",
        "global_sim": "全局仿真设置",
        "sim_delay": "仿真延迟 (ms) - 控制播放速度",
        "set_tls": "设置交通信号灯 (TLS) 参数",
        "no_tls_data": "尚未检测到信号灯数据。请确保路网已生成且包含信号灯。",
        "tls_map": "🗺️ 信号灯分布 (红色方块)",
        "select_tls": "选择信号灯 (TLS ID)",
        "editing": "正在编辑:",
        "type": "类型 (Type)",
        "offset": "相位偏移 (Offset) [秒/s]",
        "max_gap": "最大车流间隙 (Max Gap) [s]",
        "legend": "ℹ️ 信号灯状态说明 (Legend)",
        "phases": "相位列表 (Phases)",
        "connections": "🔗 信号灯控制连接 (Connections)",
        "validate_btn": "✅ 检查相位配置 (Validate Phases)",
        "start_sim": "🚀 启动仿真",
        "results_title": "📊 仿真结果分析",
        "refresh_det": "🔄 读取/刷新 检测器数据",
        "chart_title": "📈 各路段平均速度 (仅显示有车路段)",
        "no_det_file": "⚠️ 尚未找到检测器文件 (det_out.xml)。请先启动仿真并等待至少 60 秒。",
        "success_read": "成功读取数据，共 {count} 条记录",
        "wait_data": "检测器文件存在，但还没有数据写入 (SUMO 默认每60秒写入一次)。",
        "no_veh": "当前还没有车辆通过检测器 (或者仿真刚开始不到60秒)。",
        "valid_phases": "✅ 相位配置有效！",
        "invalid_phases": "❌ 发现错误:",
        "err_duration": "第 {i} 行: 时长必须大于 0",
        "err_len": "第 {i} 行: 状态长度错误 (当前: {len}, 预期: {exp})",
        "err_char": "第 {i} 行: 包含无效字符 (仅允许 G, g, y, r)",
        "dir_s": "直行 (s)", "dir_l": "左转 (l)", "dir_r": "右转 (r)", "dir_t": "掉头 (t)", "dir_L": "左偏 (L)",
        "dir_R": "右偏 (R)",
        "current_turns": "当前对话轮数",
        "err_same_edge": "起点终点相同！",
        "err_time_order": "结束时间必须大于开始时间",
        "err_ratio_sum": "车辆比例之和必须为 1.0 (当前: {val:.2f})",
        "success_add_flow": "已添加: {src} -> {dst}",
        "warn_no_flow": "请至少添加一组流量",
        "total_cycle": "当前总周期: {val} 秒",
        "no_conn_info": "未找到连接信息 (请重新生成路网以获取详细信息)",
        "err_sumo_home": "严重错误: 环境变量 'SUMO_HOME' 未设置。请配置好 SUMO 后再运行。",
        "err_sumo_home_short": "SUMO_HOME 未配置，无法执行。",
        "warn_empty_nodes": "节点坐标列表为空，无法创建路网。",
        "warn_no_edges": "没有有效的道路连接，无法生成路网。",
        "err_netconvert": "netconvert 执行失败: {e}",
        "plot_naming_ex": "命名示例: E_0_to_1",
        "plot_net_preview": "路网边预览",
        "plot_net_tls": "含信号灯的路网 (红色方块)",
        "err_net_not_found": "❌ 路网文件 '{file}' 不存在。",
        "success_gui_start": "✅ SUMO-GUI 已启动 (Delay: {delay}ms)。",
        "err_gui_start": "启动 GUI 出错: {e}",
        "err_ai": "AI Error: {e}",
        "err_ai_fix": "AI Fix Error: {e}",
        "col_speed": "速度 (m/s)",
        "col_lanes": "车道数",
        "warn_input_feedback": "请先输入修改意见。",
        "spinner_ai_fixing": "AI 正在根据您的意见调整路网...",
        "success_net_updated": "路网已更新！",
        "err_ai_update_fail": "AI 更新失败，未能解析返回数据。",
        "err_ai_call_fail": "AI 调用失败。",
        "lbl_veh_len": "车长 (m)",
        "lbl_max_speed": "最大速度 (m/s)",
        "lbl_max_accel": "最大加速度 (m/s²)",
        "lbl_max_decel": "常规最大减速度 (m/s²)",
        "lbl_cf_model": "跟驰模型 (Car-Following)",
        "lbl_min_gap": "最小车头间距 (minGap)",
        "lbl_tau": "驾驶员反应时间 (tau)",
        "lbl_sigma": "驾驶员不完美度 (sigma)",
        "lbl_delta": "加速度指数 (delta)",
        "lbl_stepping": "内部步长 (stepping)",
        "lbl_security": "安全距离因子 (security)",
        "lbl_estimation": "估计误差因子 (estimation)",
        "header_lc_params": "🛣️ 换道模型参数 (Lane Changing)",
        "lbl_lc_strat": "换道积极性 (lcStrategic)",
        "lbl_lc_coop": "协作性 (lcCooperative)",
        "lbl_lc_gain": "速度收益 (lcSpeedGain)",
        "lbl_lc_right": "靠右行驶 (lcKeepRight)",
        "lbl_lc_assert": "激进程度 (lcAssertive)",
        "caption_merging_tls": "正在合并信号灯配置到路网...",
        "err_merge_tls": "合并信号灯配置失败 (netconvert error): {e}",
        "err_read_file": "读取文件出错: {e}",
        "help_max_gap": "超过此间隙认为无车，切换相位",
        "help_state": "G=绿灯, y=黄灯, r=红灯",
        "help_sim_delay": "值越大越慢",
        "help_sigma": "0=完美驾驶, 1=完全随机",
        "help_delta": "通常为4.0",
        "help_stepping": "IDM模型的内部更新步长",
        "help_lc_strat": "为了到达目的地而换道的意愿",
        "help_lc_coop": "为了帮助他人换道而减速的意愿",
        "help_lc_gain": "为了获得速度优势而换道的意愿",
        "help_lc_right": "遵守靠右行驶规则的程度",
        "help_lc_assert": "接受更小的安全间隙 (>=1.0)",
        "tls_state_G": "**G** (大写): 绿灯 (优先通行)",
        "tls_state_g": "**g** (小写): 绿灯 (让行/左转)",
        "tls_state_y": "**y**: 黄灯",
        "tls_state_r": "**r**: 红灯",
        "ai_verify_failed": "⚠️ AI交叉验证失败",
        "ai_verify_failed_reason": "验证失败原因: {reason}",
        "ai_verify_using_ai1": "将使用AI1的原始方案继续。",
        "ai_verify_continue_btn": "✅ 我已了解，进入下一步",
        "gen_detectors": "📝 生成检测器逻辑 (Generate Detectors)",
        "api_key_ai2": "AI2 API Key (用于验证)"
    },
    "en": {
        "title": "🚦 SUMO Interactive Designer",
        "settings": "🔑 Settings",
        "reset": "🔄 Reset All",
        "step1_title": "Step 1: Generate Network Structure",
        "desc_label": "Description:",
        "desc_default": "Generate a triangular network, 2 lanes each way",
        "img_label": "Sketch (Node IDs can be marked, starting from 0):",
        "gen_btn": "🔮 Generate Preview",
        "need_api": "API Key Required",
        "ai_parsing": "AI is parsing...",
        "step2_title": "Step 2: Confirm Network Structure",
        "net_preview": "🗺️ Network Preview",
        "edge_edit": "📝 Edit Edge Attributes",
        "check_hint": "Please check if the network matches your expectation. If there are errors, describe them below for AI to fix.",
        "feedback_label": "💬 Feedback for AI (e.g., 'Missing road between 0 and 2'):",
        "fix_btn": "🛠️ Submit Fix Request",
        "confirm_btn": "✅ Confirm & Next",
        "back_btn": "⬅️ Back to Previous Step",
        "step3_title": "Step 3: Confirm Network & Add Traffic",
        "net_preview_lbl": "🗺️ Network Preview (Blue Labels = Edge ID)",
        "flow_config": "🚗 Traffic Configuration",
        "src_edge": "From Edge",
        "dst_edge": "To Edge",
        "veh_count": "Vehicle Count",
        "start_time": "Start Time (s)",
        "end_time": "End Time (s)",
        "veh_ratio": "🚙 Vehicle Composition (0.0 - 1.0)",
        "car": "Car", "truck": "Truck", "bus": "Bus", "moto": "Motorcycle",
        "add_flow": "➕ Add Flow Group",
        "clear_flow": "❌ Clear List",
        "next_step4": "Next: Fine-tuning (Step 4)",
        "step4_title": "Step 4: Simulation Fine-tuning",
        "veh_params": "🔧 Vehicle Parameters",
        "select_type": "Select Vehicle Type",
        "tab_tls": "🚦 Traffic Lights",
        "tab_phys": "🚙 Physics",
        "tab_model": "🧠 Driver Model",
        "tab_sim": "⚙️ Sim Settings",
        "global_sim": "Global Simulation Settings",
        "sim_delay": "Sim Delay (ms) - Playback Speed",
        "set_tls": "Configure Traffic Lights (TLS)",
        "no_tls_data": "No TLS data found. Ensure network is generated and contains traffic lights.",
        "tls_map": "🗺️ TLS Map (Red Squares)",
        "select_tls": "Select TLS ID",
        "editing": "Editing:",
        "type": "Type",
        "offset": "Phase Offset [s]",
        "max_gap": "Max Gap [s]",
        "legend": "ℹ️ Signal State Legend",
        "phases": "Phase List",
        "connections": "🔗 Controlled Connections",
        "validate_btn": "✅ Validate Phases",
        "start_sim": "🚀 Start Simulation",
        "results_title": "📊 Simulation Results",
        "refresh_det": "🔄 Read/Refresh Detector Data",
        "chart_title": "📈 Average Speed by Edge (Active Only)",
        "no_det_file": "⚠️ Detector file (det_out.xml) not found. Start sim and wait >60s.",
        "success_read": "Successfully read {count} records",
        "wait_data": "Detector file exists but is empty (SUMO writes every 60s).",
        "no_veh": "No vehicles recorded yet (or sim < 60s).",
        "valid_phases": "✅ Phases are valid!",
        "invalid_phases": "❌ Errors found:",
        "err_duration": "Row {i}: Duration must be > 0",
        "err_len": "Row {i}: State length error (Current: {len}, Expected: {exp})",
        "err_char": "Row {i}: Invalid characters (Only G, g, y, r allowed)",
        "dir_s": "Straight (s)", "dir_l": "Left (l)", "dir_r": "Right (r)", "dir_t": "Turnaround (t)",
        "dir_L": "Left-bear (L)", "dir_R": "Right-bear (R)",
        "current_turns": "Current Dialog Turns",
        "err_same_edge": "Start and End edges are the same!",
        "err_time_order": "End time must be greater than start time",
        "err_ratio_sum": "Sum of vehicle ratios must be 1.0 (Current: {val:.2f})",
        "success_add_flow": "Added: {src} -> {dst}",
        "warn_no_flow": "Please add at least one flow group",
        "total_cycle": "Current Total Cycle: {val} s",
        "no_conn_info": "No connection info found (Regenerate network to get details)",
        "err_sumo_home": "Critical Error: 'SUMO_HOME' environment variable not set. Please configure SUMO before running.",
        "err_sumo_home_short": "SUMO_HOME not configured, cannot execute.",
        "warn_empty_nodes": "Node coordinate list is empty, cannot create network.",
        "warn_no_edges": "No valid edge connections, cannot generate network.",
        "err_netconvert": "netconvert failed: {e}",
        "plot_naming_ex": "Naming Ex: E_0_to_1",
        "plot_net_preview": "Network Edges Preview",
        "plot_net_tls": "Network with Traffic Lights (Red Squares)",
        "err_net_not_found": "❌ Network file '{file}' not found.",
        "success_gui_start": "✅ SUMO-GUI Started (Delay: {delay}ms).",
        "err_gui_start": "Error starting GUI: {e}",
        "err_ai": "AI Error: {e}",
        "err_ai_fix": "AI Fix Error: {e}",
        "col_speed": "Speed (m/s)",
        "col_lanes": "Lanes",
        "warn_input_feedback": "Please enter feedback first.",
        "spinner_ai_fixing": "AI is adjusting the network based on your feedback...",
        "success_net_updated": "Network updated!",
        "err_ai_update_fail": "AI update failed, could not parse returned data.",
        "err_ai_call_fail": "AI call failed.",
        "lbl_veh_len": "Length (m)",
        "lbl_max_speed": "Max Speed (m/s)",
        "lbl_max_accel": "Max Accel (m/s²)",
        "lbl_max_decel": "Max Decel (m/s²)",
        "lbl_cf_model": "Car-Following Model",
        "lbl_min_gap": "Min Gap (minGap)",
        "lbl_tau": "Driver Reaction Time (tau)",
        "lbl_sigma": "Driver Imperfection (sigma)",
        "lbl_delta": "Acceleration Exponent (delta)",
        "lbl_stepping": "Internal Step Length (stepping)",
        "lbl_security": "Security Distance Factor (security)",
        "lbl_estimation": "Estimation Error Factor (estimation)",
        "header_lc_params": "🛣️ Lane Changing Parameters",
        "lbl_lc_strat": "Strategic Change (lcStrategic)",
        "lbl_lc_coop": "Cooperative Change (lcCooperative)",
        "lbl_lc_gain": "Speed Gain Change (lcSpeedGain)",
        "lbl_lc_right": "Keep Right (lcKeepRight)",
        "lbl_lc_assert": "Assertiveness (lcAssertive)",
        "caption_merging_tls": "Merging TLS configuration into network...",
        "err_merge_tls": "Failed to merge TLS configuration (netconvert error): {e}",
        "err_read_file": "Error reading file: {e}",
        "help_max_gap": "Switch phase when gap exceeds this threshold",
        "help_state": "G=Green, y=Yellow, r=Red",
        "help_sim_delay": "Higher value = slower playback",
        "help_sigma": "0=Perfect driving, 1=Completely random",
        "help_delta": "Typically 4.0",
        "help_stepping": "IDM internal update step length",
        "help_lc_strat": "Willingness to change lanes to reach destination",
        "help_lc_coop": "Willingness to slow down to help others change lanes",
        "help_lc_gain": "Willingness to change lanes for speed advantage",
        "help_lc_right": "Degree of adherence to keep-right rule",
        "help_lc_assert": "Accept smaller safety gaps (>=1.0)",
        "tls_state_G": "**G** (uppercase): Green light (priority)",
        "tls_state_g": "**g** (lowercase): Green light (yield/left turn)",
        "tls_state_y": "**y**: Yellow light",
        "tls_state_r": "**r**: Red light",
        "ai_verify_failed": "⚠️ AI Cross-verification Failed",
        "ai_verify_failed_reason": "Failure reason: {reason}",
        "ai_verify_using_ai1": "Will use AI1's original solution to continue.",
        "ai_verify_continue_btn": "✅ I understand, proceed to next step",
        "gen_detectors": "📝 Generate Detectors",
        "api_key_ai2": "AI2 API Key (for verification)"
    }
}


def t(key, **kwargs):
    lang = st.session_state.get("lang", "zh")
    text = TRANSLATIONS.get(lang, TRANSLATIONS["zh"]).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text