import streamlit as st

TRANSLATIONS = {
    "zh": {
        "title": "🚦 TopoGen: 多模态双智能体自动化仿真生成框架",
        "settings": "⚙️ 框架设置",
        "reset": "🔄 重置框架",
        "step1_title": "阶段 1: 多模态意图摄取 (Intent Ingestion)",
        "desc_label": "叙述性设计需求:",
        "desc_default": "生成一个复杂的十字路口，每个方向包含3条车道。",
        "img_label": "空间布局草图 (支持节点编号与边长标注):",
        "gen_btn": "🔮 生成拓扑预览 (GIR)",
        "need_api": "需要 API Key 以启动推理层",
        "ai_parsing": "生成器 (Generator) 正在将意图映射为图表征...",
        "step2_title": "阶段 2: 拓扑对齐与精细化修正 (Grounding & Refinement)",
        "net_preview": "🗺️ 拓扑图可视化 (GIR Preview)",
        "edge_edit": "📝 符号属性对齐 (Edge Attributes)",
        "check_hint": "请检查生成的拓扑结构是否符合设计意图。如有逻辑偏差，请通过下方对话框进行干预。",
        "feedback_label": "💬 语言干预 (例如: '在节点0和2之间增加一条单向路'):",
        "fix_btn": "🛠️ 提交修正建议",
        "confirm_btn": "✅ 确认拓扑逻辑，进入下一步",
        "back_btn": "⬅️ 返回上一步",
        "step3_title": "阶段 3: 交通需求映射 (Demand Mapping)",
        "net_preview_lbl": "🗺️ 物理编译前的拓扑检查",
        "flow_config": "🚗 动态交通流配置",
        "src_edge": "起始边 (Source)",
        "dst_edge": "目标边 (Sink)",
        "veh_count": "车辆总数",
        "start_time": "进入时间 (s)",
        "end_time": "结束时间 (s)",
        "veh_ratio": "🚙 车队构成比例 (0.0 - 1.0)",
        "car": "轿车", "truck": "货车", "bus": "公交", "moto": "摩托",
        "add_flow": "➕ 增加需求组",
        "clear_flow": "❌ 清空需求列表",
        "next_step4": "下一步: 仿真编排 (Phase 4)",
        "step4_title": "阶段 4: 仿真编排与技能执行 (Orchestration & Execution)",
        "veh_params": "🔧 微观行为参数配置",
        "select_type": "选择目标车型",
        "tab_tls": "🚦 信号逻辑 (TLS)",
        "tab_phys": "🚙 运动学参数",
        "tab_model": "🧠 跟驰/换道模型",
        "tab_sim": "⚙️ 执行设置",
        "global_sim": "全局仿真环境编排",
        "sim_delay": "步长延迟 (ms) - 控制回放节奏",
        "set_tls": "配置交通信号灯时序逻辑",
        "no_tls_data": "未检测到信号灯。请确保路网结构包含连接度>=3的交叉口。",
        "tls_map": "🗺️ 信控节点分布 (红色标识)",
        "select_tls": "选择信控 ID",
        "editing": "正在编辑:",
        "type": "程序类型 (Type)",
        "offset": "相位偏移 (Offset) [s]",
        "max_gap": "最大车流间隙 (Max Gap) [s]",
        "legend": "ℹ️ 信号状态图例说明",
        "phases": "相位列表 (Phase List)",
        "connections": "🔗 受控车道连接映射",
        "validate_btn": "✅ 验证时序逻辑合法性",
        "start_sim": "🚀 启动仿真 (Skill-based Acting)",
        "results_title": "📊 仿真性能分析与反馈",
        "refresh_det": "🔄 读取检测器实时数据",
        "chart_title": "📈 路段平均速度分布 (物理落地验证)",
        "no_det_file": "⚠️ 未找到检测器数据。请先启动仿真并等待数据写入。",
        "success_read": "成功获取 {count} 条监测记录",
        "wait_data": "检测器已就绪，正在等待数据写入周期...",
        "no_veh": "当前无车辆通过监测区域。",
        "valid_phases": "✅ 相位配置符合逻辑！",
        "invalid_phases": "❌ 发现拓扑/时序错误:",
        "err_duration": "第 {i} 行: 持续时间必须大于 0",
        "err_len": "第 {i} 行: 状态字符长度错误 (预期: {exp})",
        "err_char": "第 {i} 行: 包含无效字符 (仅限 G, g, y, r)",
        "dir_s": "直行 (s)", "dir_l": "左转 (l)", "dir_r": "右转 (r)", "dir_t": "掉头 (t)", "dir_L": "左偏 (L)",
        "dir_R": "右偏 (R)",
        "current_turns": "当前协商轮数 (Negotiation Rounds)",
        "err_same_edge": "源边与目标边不能相同！",
        "err_time_order": "结束时间必须大于开始时间",
        "err_ratio_sum": "构成比例之和必须为 1.0 (当前: {val:.2f})",
        "success_add_flow": "已添加需求: {src} -> {dst}",
        "warn_no_flow": "请至少配置一组交通需求",
        "total_cycle": "当前总周期: {val} 秒",
        "no_conn_info": "未提取到连接映射信息",
        "err_sumo_home": "严重错误: 环境变量 'SUMO_HOME' 未设置。",
        "err_sumo_home_short": "SUMO 路径配置错误。",
        "warn_empty_nodes": "节点坐标列表为空，无法构建 GIR。",
        "warn_no_edges": "无有效边连接，无法编译路网。",
        "err_netconvert": "netconvert 物理编译失败: {e}",
        "plot_naming_ex": "命名示例: E_0_to_1",
        "plot_net_preview": "拓扑结构预览 (GIR Visualization)",
        "plot_net_tls": "含信控节点的拓扑布局",
        "err_net_not_found": "❌ 路网文件 '{file}' 缺失。",
        "success_gui_start": "✅ SUMO-GUI 编排成功 (延迟: {delay}ms)。",
        "err_gui_start": "执行引擎启动失败: {e}",
        "err_ai": "推理层错误: {e}",
        "err_ai_fix": "修正逻辑执行失败: {e}",
        "col_speed": "限速 (m/s)",
        "col_lanes": "车道数",
        "warn_input_feedback": "请输入干预指令。",
        "spinner_ai_fixing": "生成器正在根据反馈更新拓扑模型...",
        "success_net_updated": "拓扑逻辑已更新！",
        "err_ai_update_fail": "模型更新失败，未能生成有效 JSON。",
        "err_ai_call_fail": "大模型连接中断。",
        "lbl_veh_len": "车身长度 (m)",
        "lbl_max_speed": "期望速度 (m/s)",
        "lbl_max_accel": "最大加速度 (m/s²)",
        "lbl_max_decel": "舒适减速度 (m/s²)",
        "lbl_cf_model": "跟驰动力学模型",
        "lbl_min_gap": "最小安全间距 (minGap)",
        "lbl_tau": "驾驶员反应时间 (tau)",
        "lbl_sigma": "驾驶行为随机性 (sigma)",
        "lbl_delta": "加速度指数 (delta)",
        "lbl_stepping": "更新步长 (stepping)",
        "lbl_security": "安全因子 (security)",
        "lbl_estimation": "估计误差因子 (estimation)",
        "header_lc_params": "🛣️ 换道模型策略超参数",
        "lbl_lc_strat": "换道积极性 (lcStrategic)",
        "lbl_lc_coop": "协作因子 (lcCooperative)",
        "lbl_lc_gain": "速度收益偏好 (lcSpeedGain)",
        "lbl_lc_right": "靠右行驶程度 (lcKeepRight)",
        "lbl_lc_assert": "激进程度 (lcAssertive)",
        "caption_merging_tls": "正在将信控逻辑合并至物理路网文件...",
        "err_merge_tls": "信控合并失败: {e}",
        "err_read_file": "文件读取异常: {e}",
        "help_max_gap": "超过此间隙则切换相位",
        "help_state": "G=绿灯, y=黄灯, r=红灯",
        "help_sim_delay": "值越大回放越慢",
        "help_sigma": "0=完美驾驶, 1=完全随机",
        "help_delta": "典型值为 4.0",
        "help_stepping": "IDM 模型的内部更新步长",
        "help_lc_strat": "为了到达目的地而换道的意愿",
        "help_lc_coop": "为了帮助他人换道而减速的意愿",
        "help_lc_gain": "为了获得速度优势而换道的意愿",
        "help_lc_right": "遵守靠右行驶规则的程度",
        "help_lc_assert": "接受更小的安全间隙 (>=1.0)",
        "tls_state_G": "**G**: 优先通行绿灯",
        "tls_state_g": "**g**: 需让行绿灯",
        "tls_state_y": "**y**: 黄灯",
        "tls_state_r": "**r**: 红灯",
        "ai_verify_failed": "⚠️ 拓扑验证未达成共识",
        "ai_verify_failed_reason": "审核失败原因: {reason}",
        "ai_verify_using_ai1": "系统将保留生成器的初始方案。",
        "ai_verify_continue_btn": "✅ 接受当前方案并继续",
        "gen_detectors": "📝 自动布置感应线圈 (Generate Detectors)",
        "api_key_ai2": "审核器 (Auditor) API Key",
        "select_model": "🤖 选择 MLLM 基座",
        "input_api_key": "🔑 输入 {model} 的 API Key",
        "temp_label": "🌡️ 推理随机性 (Temperature)",
        "temp_help": "较低值(0.1)更严谨，较高值(0.8)更具创造性。",
        "ai_check_label": "🤖 启用双智能体协商机制 (Dual-Agent Negotiation)",
        "ai_check_help": "开启后，审核器 (Auditor) 将对生成器 (Generator) 的输出进行对抗性审计，通过多轮博弈消除拓扑幻觉。",
        "flow_table_header": "📋 交通流需求矩阵",
        "flow_table_hint": "提示: 选中行按 Delete 删除；双击单元格可微调。",
        "col_from": "起点 (From)",
        "col_to": "终点 (To)",
        "col_count": "流量",
        "col_start": "开始 (s)",
        "col_end": "结束 (s)",
        "col_car": "轿车占比",
        "col_truck": "货车占比",
        "col_bus": "公交占比",
        "col_moto": "摩托占比",
        "apply_tls_changes": "💾 应用信控逻辑修改",
        "tls_saved_success": "✅ 信号灯配置已成功更新！"
    },
    "en": {
        "title": "🚦 TopoGen: Multi-modal Dual-Agent for Autonomous Simulation",
        "settings": "⚙️ Framework Settings",
        "reset": "🔄 Reset Framework",
        "step1_title": "Phase 1: Multi-modal Intent Ingestion",
        "desc_label": "Narrative Design Requirements:",
        "desc_default": "Generate a complex intersection with 3 lanes per direction.",
        "img_label": "Spatial Layout Sketch (Supports Node IDs and Edge Lengths):",
        "gen_btn": "🔮 Generate Topological Preview (GIR)",
        "need_api": "API Key Required for Reasoning Layer",
        "ai_parsing": "Generator is mapping intent to graph representation...",
        "step2_title": "Phase 2: Topological Grounding & Refinement",
        "net_preview": "🗺️ GIR Visualization",
        "edge_edit": "📝 Symbolic Attribute Alignment",
        "check_hint": "Verify the synthesized graph. Use linguistic intervention to resolve any logical inconsistencies.",
        "feedback_label": "💬 Linguistic Feedback (e.g., 'Add a lane to road 0-1'):",
        "fix_btn": "🛠️ Submit Refinement Request",
        "confirm_btn": "✅ Confirm Topology & Proceed",
        "back_btn": "⬅️ Back to Ingestion",
        "step3_title": "Phase 3: Traffic Demand Mapping",
        "net_preview_lbl": "🗺️ Pre-compilation Topological Check",
        "flow_config": "🚗 Dynamic Traffic Demand Configuration",
        "src_edge": "Source Edge",
        "dst_edge": "Sink Edge",
        "veh_count": "Total Volume",
        "start_time": "Start (s)",
        "end_time": "End (s)",
        "veh_ratio": "🚙 Vehicle Fleet Composition (0.0 - 1.0)",
        "car": "Car", "truck": "Truck", "bus": "Bus", "moto": "Moto",
        "add_flow": "➕ Append Demand Group",
        "clear_flow": "❌ Clear Demand Matrix",
        "next_step4": "Next: Simulation Orchestration",
        "step4_title": "Phase 4: Simulation Orchestration & Execution",
        "veh_params": "🔧 Microscopic Behavior Configuration",
        "select_type": "Focus Vehicle Type",
        "tab_tls": "🚦 Signal Logic (TLS)",
        "tab_phys": "🚙 Kinematics",
        "tab_model": "🧠 Driver Models",
        "tab_sim": "⚙️ Execution",
        "global_sim": "Global Environment Orchestration",
        "sim_delay": "Execution Delay (ms) - Playback Pace",
        "set_tls": "Configure Signal Timing Logic",
        "no_tls_data": "No TLS detected. Ensure junctions have connectivity degree >= 3.",
        "tls_map": "🗺️ Signalized Node Distribution",
        "select_tls": "Select TLS ID",
        "editing": "Editing:",
        "type": "Program Type",
        "offset": "Phase Offset [s]",
        "max_gap": "Max Gap [s]",
        "legend": "ℹ️ Signal State Legend",
        "phases": "Phase List",
        "connections": "🔗 Controlled Connection Mapping",
        "validate_btn": "✅ Validate Temporal Logic",
        "start_sim": "🚀 Start Simulation (Skill-based Acting)",
        "results_title": "📊 Performance Analytics & Feedback",
        "refresh_det": "🔄 Fetch Real-time Metrics",
        "chart_title": "📈 Average Speed Distribution (Physical Grounding Verification)",
        "no_det_file": "⚠️ No detector data found. Start simulation and wait for the write cycle.",
        "success_read": "Successfully fetched {count} records",
        "wait_data": "Detectors active. Waiting for buffer flush...",
        "no_veh": "No vehicle detections in the current cycle.",
        "valid_phases": "✅ Signal logic is consistent!",
        "invalid_phases": "❌ Logical fallacies found:",
        "err_duration": "Row {i}: Duration must be > 0",
        "err_len": "Row {i}: State length mismatch (Expected: {exp})",
        "err_char": "Row {i}: Invalid characters (Only G, g, y, r allowed)",
        "dir_s": "Straight (s)", "dir_l": "Left (l)", "dir_r": "Right (r)", "dir_t": "Turnaround (t)",
        "dir_L": "Left-bear (L)", "dir_R": "Right-bear (R)",
        "current_turns": "Negotiation Rounds Completed",
        "err_same_edge": "Source and Sink edges must differ!",
        "err_time_order": "End time must exceed start time",
        "err_ratio_sum": "Fleet composition must sum to 1.0 (Current: {val:.2f})",
        "success_add_flow": "Demand added: {src} -> {dst}",
        "warn_no_flow": "At least one traffic flow group is required.",
        "total_cycle": "Current Cycle Duration: {val} s",
        "no_conn_info": "No connection metadata extracted.",
        "err_sumo_home": "Critical Error: 'SUMO_HOME' not set.",
        "err_sumo_home_short": "SUMO path misconfigured.",
        "warn_empty_nodes": "Node list is empty. Cannot build GIR.",
        "warn_no_edges": "No valid connections. Compilation aborted.",
        "err_netconvert": "netconvert compilation failed: {e}",
        "plot_naming_ex": "Naming Ex: E_0_to_1",
        "plot_net_preview": "GIR Visualization",
        "plot_net_tls": "Topology with Signalized Junctions",
        "err_net_not_found": "❌ Network artifact '{file}' missing.",
        "success_gui_start": "✅ SUMO-GUI Orchestrated (Delay: {delay}ms).",
        "err_gui_start": "Engine launch failed: {e}",
        "err_ai": "Reasoning Layer Error: {e}",
        "err_ai_fix": "Refinement execution failed: {e}",
        "col_speed": "Limit (m/s)",
        "col_lanes": "Lanes",
        "warn_input_feedback": "Please provide instruction.",
        "spinner_ai_fixing": "Generator is updating topological model via feedback...",
        "success_net_updated": "Topology updated successfully!",
        "err_ai_update_fail": "Update failed. Failed to synthesize valid JSON.",
        "err_ai_call_fail": "Model connection lost.",
        "lbl_veh_len": "Length (m)",
        "lbl_max_speed": "Desired Speed (m/s)",
        "lbl_max_accel": "Max Accel (m/s²)",
        "lbl_max_decel": "Max Decel (m/s²)",
        "lbl_cf_model": "Car-Following Model",
        "lbl_min_gap": "Minimum Gap (minGap)",
        "lbl_tau": "Reaction Latency (tau)",
        "lbl_sigma": "Driver Imperfection (sigma)",
        "lbl_delta": "Acceleration Exponent (delta)",
        "lbl_stepping": "Internal Stepping",
        "lbl_security": "Security Factor",
        "lbl_estimation": "Estimation Error",
        "header_lc_params": "🛣️ Lane-Changing Strategy Hyperparameters",
        "lbl_lc_strat": "Strategic Change (lcStrategic)",
        "lbl_lc_coop": "Cooperation Factor (lcCooperative)",
        "lbl_lc_gain": "Speed Gain Preference (lcSpeedGain)",
        "lbl_lc_right": "Keep Right Adherence (lcKeepRight)",
        "lbl_lc_assert": "Assertiveness (lcAssertive)",
        "caption_merging_tls": "Merging temporal logic into physical network...",
        "err_merge_tls": "TLS Merge failed: {e}",
        "err_read_file": "File ingestion error: {e}",
        "help_max_gap": "Phase switch threshold",
        "help_state": "G=Green, y=Yellow, r=Red",
        "help_sim_delay": "Higher = slower execution",
        "help_sigma": "0=Perfect, 1=Stochastic",
        "help_delta": "Typically 4.0",
        "help_stepping": "Internal step for IDM",
        "help_lc_strat": "Willingness to change lanes for destination",
        "help_lc_coop": "Willingness to slow down for others",
        "help_lc_gain": "Preference for faster lanes",
        "help_lc_right": "Adherence to keep-right rule",
        "help_lc_assert": "Acceptance of smaller safety gaps (>=1.0)",
        "tls_state_G": "**G**: Priority green",
        "tls_state_g": "**g**: Yielding green",
        "tls_state_y": "**y**: Yellow",
        "tls_state_r": "**r**: Red",
        "ai_verify_failed": "⚠️ Negotiation Stalemate",
        "ai_verify_failed_reason": "Stalemate Reason: {reason}",
        "ai_verify_using_ai1": "Reverting to initial Generator proposal.",
        "ai_verify_continue_btn": "✅ Accept Current & Proceed",
        "gen_detectors": "📝 Automated Sensor Deployment",
        "api_key_ai2": "Auditor API Key",
        "select_model": "🤖 Select MLLM Backbone",
        "input_api_key": "🔑 Enter {model} API Key",
        "temp_label": "🌡️ Reasoning Temperature",
        "temp_help": "Lower (0.1) for precision, Higher (0.8) for creativity.",
        "ai_check_label": "🤖 Enable Dual-Agent Negotiation",
        "ai_check_help": "Activates the Auditor agent to perform adversarial auditing on the Generator, mitigating hallucinations through iterative negotiation.",
        "flow_table_header": "📋 Traffic Demand Matrix",
        "flow_table_hint": "Hint: Select row & press Delete to remove; double-click cell to tune.",
        "col_from": "From",
        "col_to": "To",
        "col_count": "Volume",
        "col_start": "Start (s)",
        "col_end": "End (s)",
        "col_car": "Car %",
        "col_truck": "Truck %",
        "col_bus": "Bus %",
        "col_moto": "Moto %",
        "apply_tls_changes": "💾 Apply Signal Logic Changes",
        "tls_saved_success": "✅ Signal logic updated successfully!"
    }
}

def t(key, **kwargs):
    lang = st.session_state.get("lang", "en") # 默认设为英文更符合 GitHub
    text = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text